// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsManagement.Context;

#nullable disable

namespace SportsManagement.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20231116080418_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsManagement.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("branch_name");

                    b.HasKey("Id");

                    b.ToTable("Branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchName = "Football"
                        });
                });

            modelBuilder.Entity("SportsManagement.Models.Outfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("outfit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("outfit_brand_name");

                    b.Property<short>("No")
                        .HasColumnType("smallint")
                        .HasColumnName("outfit_no");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("outfit_type");

                    b.HasKey("Id");

                    b.ToTable("Outfits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Adidas",
                            No = (short)42,
                            PlayerId = 1,
                            Type = 0
                        });
                });

            modelBuilder.Entity("SportsManagement.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("player_age");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("player_name");

                    b.Property<int>("OutfitId")
                        .HasColumnType("int")
                        .HasColumnName("outfit_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("player_price");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            BranchId = 1,
                            Name = "Icardi",
                            OutfitId = 1,
                            Price = 3000000m,
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("SportsManagement.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("team_name");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeamName = "Galatasaray"
                        });
                });

            modelBuilder.Entity("SportsManagement.Models.Player", b =>
                {
                    b.HasOne("SportsManagement.Models.Branch", "Branch")
                        .WithMany("Players")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.Models.Outfit", "Outfit")
                        .WithOne("Player")
                        .HasForeignKey("SportsManagement.Models.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsManagement.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Outfit");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportsManagement.Models.Branch", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("SportsManagement.Models.Outfit", b =>
                {
                    b.Navigation("Player")
                        .IsRequired();
                });

            modelBuilder.Entity("SportsManagement.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
